---
kind: pipeline
name: deploy to swarm-test.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      host: swarm-test.autonomic.zone
      stack: custom-php
      generate_secrets: true
      purge: true
      deploy_key:
        from_secret: drone_ssh_swarm_test
    environment:
      DOMAIN: custom-php.swarm-test.autonomic.zone
      STACK_NAME: custom-php
      LETS_ENCRYPT_ENV: production
      SECRET_DB_PASSWORD_VERSION: v1
      SECRET_DB_ROOT_PASSWORD_VERSION: v1
      PHP_UPLOADS_CONF_VERSION: v1
      ENTRYPOINT_CONF_VERSION: v1
trigger:
  branch:
    - master
---
kind: pipeline
name: recipe release
steps:
  - name: release a new version
    image: thecoopcloud/drone-abra:latest
    settings:
      command: recipe wordpress release
      deploy_key:
        from_secret: abra_bot_deploy_key
